import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/FontVariantNumeric_TabularNums.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Fonts Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          font-variant-numeric: <u>tabular-nums</u>
        </h1>

        <div className={styles.description}>
            <p>Supported font family: Circular</p>
            <code><a href="https://lineto.com/typefaces/circular/technical">https://lineto.com/typefaces/circular/technical</a></code>
        </div>

        <div className={`${styles.grid}`}>
            <div className={`content`}>
                <h2>Tabular numbers</h2>
                <table className={styles.tableTabular}>
                    <thead>
                        <tr>
                            <th>One</th>
                            <th>Two</th>
                            <th>Three</th>
                            <th>Four</th>
                            <th>Five</th>
                            <th>Six</th>
                            <th>Seven</th>
                            <th>Eight</th>
                            <th>Nine</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <span className={styles.tableSpan}>1<span className={styles.tableContentLine}></span></span>
                            </td>
                            <td>
                                <span className={styles.tableSpan}>12<span className={styles.tableContentLine}></span></span>
                            </td>
                            <td>
                                <span className={styles.tableSpan}>123<span className={styles.tableContentLine}></span></span>
                            </td>
                            <td>
                                <span className={styles.tableSpan}>1234<span className={styles.tableContentLine}></span></span>
                            </td>
                            <td>
                                <span className={styles.tableSpan}>12345<span className={styles.tableContentLine}></span></span>
                            </td>
                            <td>
                                <span className={styles.tableSpan}>123456<span className={styles.tableContentLine}></span></span>
                            </td>
                            <td>
                                <span className={styles.tableSpan}>1234567<span className={styles.tableContentLine}></span></span>
                            </td>
                            <td>
                                <span className={styles.tableSpan}>12345678<span className={styles.tableContentLine}></span></span>
                            </td>
                            <td>
                                <span className={styles.tableSpan}>123456789<span className={styles.tableContentLine}></span></span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span>0</span>
                            </td>
                            <td>
                                <span>01</span>
                            </td>
                            <td>
                                <span>012</span>
                            </td>
                            <td>
                                <span>0123</span>
                            </td>
                            <td>
                                <span>01234</span>
                            </td>
                            <td>
                                <span>012345</span>
                            </td>
                            <td>
                                <span>0123456</span>
                            </td>
                            <td>
                                <span>01234567</span>
                            </td>
                            <td>
                                <span>012345678</span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span>2</span>
                            </td>
                            <td>
                                <span>23</span>
                            </td>
                            <td>
                                <span>234</span>
                            </td>
                            <td>
                                <span>2345</span>
                            </td>
                            <td>
                                <span>23456</span>
                            </td>
                            <td>
                                <span>234567</span>
                            </td>
                            <td>
                                <span>2345678</span>
                            </td>
                            <td>
                                <span>23456789</span>
                            </td>
                            <td>
                                <span>234567890</span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span>#</span>
                            </td>
                            <td>
                                <span>#2</span>
                            </td>
                            <td>
                                <span>#23</span>
                            </td>
                            <td>
                                <span>#234</span>
                            </td>
                            <td>
                                <span>#2345</span>
                            </td>
                            <td>
                                <span>#23456</span>
                            </td>
                            <td>
                                <span>#234567</span>
                            </td>
                            <td>
                                <span>#2345678</span>
                            </td>
                            <td>
                                <span>#23456789</span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span>€</span>
                            </td>
                            <td>
                                <span>€2</span>
                            </td>
                            <td>
                                <span>€23</span>
                            </td>
                            <td>
                                <span>€234</span>
                            </td>
                            <td>
                                <span>€2345</span>
                            </td>
                            <td>
                                <span>€23456</span>
                            </td>
                            <td>
                                <span>€234567</span>
                            </td>
                            <td>
                                <span>€2345678</span>
                            </td>
                            <td>
                                <span>€23456789</span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span>€</span>
                            </td>
                            <td>
                                <span>€2</span>
                            </td>
                            <td>
                                <span>€23</span>
                            </td>
                            <td>
                                <span>€2.4</span>
                            </td>
                            <td>
                                <span>€23,5</span>
                            </td>
                            <td>
                                <span>€234 6</span>
                            </td>
                            <td>
                                <span>€2345+7</span>
                            </td>
                            <td>
                                <span>€23456-8</span>
                            </td>
                            <td>
                                <span>€23 = 4.9</span>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <h2>Normal</h2>
                <table className={styles.table}>
                    <thead>
                        <tr>
                            <th>One</th>
                            <th>Two</th>
                            <th>Three</th>
                            <th>Four</th>
                            <th>Five</th>
                            <th>Six</th>
                            <th>Seven</th>
                            <th>Eight</th>
                            <th>Nine</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                        <td>
                                <span className={styles.tableSpan}>1<span className={styles.tableContentLine}></span></span>
                            </td>
                            <td>
                                <span className={styles.tableSpan}>12<span className={styles.tableContentLine}></span></span>
                            </td>
                            <td>
                                <span className={styles.tableSpan}>123<span className={styles.tableContentLine}></span></span>
                            </td>
                            <td>
                                <span className={styles.tableSpan}>1234<span className={styles.tableContentLine}></span></span>
                            </td>
                            <td>
                                <span className={styles.tableSpan}>12345<span className={styles.tableContentLine}></span></span>
                            </td>
                            <td>
                                <span className={styles.tableSpan}>123456<span className={styles.tableContentLine}></span></span>
                            </td>
                            <td>
                                <span className={styles.tableSpan}>1234567<span className={styles.tableContentLine}></span></span>
                            </td>
                            <td>
                                <span className={styles.tableSpan}>12345678<span className={styles.tableContentLine}></span></span>
                            </td>
                            <td>
                                <span className={styles.tableSpan}>123456789<span className={styles.tableContentLine}></span></span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span>0</span>
                            </td>
                            <td>
                                <span>01</span>
                            </td>
                            <td>
                                <span>012</span>
                            </td>
                            <td>
                                <span>0123</span>
                            </td>
                            <td>
                                <span>01234</span>
                            </td>
                            <td>
                                <span>012345</span>
                            </td>
                            <td>
                                <span>0123456</span>
                            </td>
                            <td>
                                <span>01234567</span>
                            </td>
                            <td>
                                <span>012345678</span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span>2</span>
                            </td>
                            <td>
                                <span>23</span>
                            </td>
                            <td>
                                <span>234</span>
                            </td>
                            <td>
                                <span>2345</span>
                            </td>
                            <td>
                                <span>23456</span>
                            </td>
                            <td>
                                <span>234567</span>
                            </td>
                            <td>
                                <span>2345678</span>
                            </td>
                            <td>
                                <span>23456789</span>
                            </td>
                            <td>
                                <span>234567890</span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span>#</span>
                            </td>
                            <td>
                                <span>#2</span>
                            </td>
                            <td>
                                <span>#23</span>
                            </td>
                            <td>
                                <span>#234</span>
                            </td>
                            <td>
                                <span>#2345</span>
                            </td>
                            <td>
                                <span>#23456</span>
                            </td>
                            <td>
                                <span>#234567</span>
                            </td>
                            <td>
                                <span>#2345678</span>
                            </td>
                            <td>
                                <span>#23456789</span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span>€</span>
                            </td>
                            <td>
                                <span>€2</span>
                            </td>
                            <td>
                                <span>€23</span>
                            </td>
                            <td>
                                <span>€234</span>
                            </td>
                            <td>
                                <span>€2345</span>
                            </td>
                            <td>
                                <span>€23456</span>
                            </td>
                            <td>
                                <span>€234567</span>
                            </td>
                            <td>
                                <span>€2345678</span>
                            </td>
                            <td>
                                <span>€23456789</span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span>€</span>
                            </td>
                            <td>
                                <span>€2</span>
                            </td>
                            <td>
                                <span>€23</span>
                            </td>
                            <td>
                                <span>€2.4</span>
                            </td>
                            <td>
                                <span>€23,5</span>
                            </td>
                            <td>
                                <span>€234.6</span>
                            </td>
                            <td>
                                <span>€2345.7</span>
                            </td>
                            <td>
                                <span>€23456.8</span>
                            </td>
                            <td>
                                <span>€234567.9</span>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
      </main>
    </div>
  )
}

export default Home
