import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/FontVariantNumeric.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Fonts Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className={styles.title}>
          font-variant-numeric
        </h1>

        {/* TODO: Make select box that changes fonts for user? */}
        {/* <p>
          <select>
            <option value="">Default</option>
            <option value="Circular">Circular</option>
            <option value="Comic Sans">Comic Sans</option>
          </select>
        </p> */}

        <div className={`grid`}>
          <div className={`card`}>
            <Link href="/font-variant-numeric/tabular-nums">
              <a>
                <h2>font-variant-numeric: <u>tabular-nums</u></h2>
                <p>Tabular numbers that can help your typography display improve.</p>
              </a>
            </Link>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
